config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :player_search, only: [:index]

  root to: 'players#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/player_search_controller.rb
class PlayerSearchController < ApplicationController
  # Ensure that our index view will only render the HTML in app/views/player_search/index.html.erb. 
  # If we don’t set layout to false, every search request we make will render our index view inside of the layout defined in app/views/layouts/application.html.erb 
  # We don’t want that since we’re planning to insert the search results into a piece of an existing page.
  layout false

  def index
    @players = Player.where("name LIKE ?", "%#{params[:search]}%")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  def index
    @players = Player.all
  end

  def show
  end

  def new
    @player = Player.new
  end

  def edit
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to @player, notice: 'Player was successfully created.'
    else
      render :new 
    end
  end

  def update
    if @player.update(player_params)
      redirect_to @player, notice: 'Player was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @player.destroy
  
    redirect_to players_url, notice: 'Player was successfully destroyed.'
  end
 
  private def set_player
    @player = Player.find(params[:id])
  end

  private def player_params
    params.require(:player).permit(:name, :sports)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/player_search_helper.rb
module PlayerSearchHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoStimulusLiveSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player_search/index.html.erb
<% @players.each do |player| %>
  <%= render partial: "players/player", locals: { player: player } %>
<% end %>

app/views/players/_form.html.erb
<%= form_with(model: player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :sports %>
    <%= form.text_field :sports %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div>
  <span><%= player.name %> ||</span>
  <span><%= player.sports %></span>
</div>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>
<p>these are the players</p>
<div data-controller="search">
  <%= render partial: "shared/search_form" %>
  <div data-search-target="results">
     <% @players.each do |player| %>
        <%= render partial: "player", locals: { player: player } %>
      <% end %>
  </div>
</div>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @player.name %>
</p>

<p>
  <strong>Sports:</strong>
  <%= @player.sports %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>

app/views/shared/_search_form.html.erb
<%= form_with url: player_search_index_path, method: :get, data: { action: "ajax:success->search#handleResults", target: "search.form" } do |form| %>
  <div>
    <%= form.text_field :search, data: { action: "input->search#search" }, autocomplete: "off" %>
  </div>
<% end %>